import Link from "next/link";
import { notFound } from "next/navigation";

const WORKFLOWS: Record<
  string,
  {
    title: string;
    description: string;
    whoThisIsFor: string[];
    tools: string[];
    steps: string[];
  }
> = {
  "web-developer": {
    title: "Web Developer",
    description:
      "Ship features faster with AI-assisted code, reviews, and deployment pipelines.",
    whoThisIsFor: [
      "Frontend and full-stack developers",
      "Dev teams shipping on tight deadlines",
      "Solo founders who code",
    ],
    tools: [
      "Claude — project briefs, proposals, contracts, debugging, documentation",
      "Cursor IDE — AI coding assistant that reads your entire codebase",
      "v0.dev — generate React UI components from plain English",
      "GitHub Copilot — autocomplete and boilerplate inside your editor",
      "Make / Zapier— connect tools, trigger automations, eliminate manual tasks",
      "Notion AI— project planning, client notes, living documentation",
      "Warp Terminal— describe shell commands in plain English",
    ],
    steps: [
      "Step 1 — Client submits intake form → Claude generates structured brief",
      "Step 2 — Brief feeds into Claude → full proposal auto-drafted in 20 min", 
      "Step 3 — Approved scope → Claude builds site architecture + component plan",
      "Step 4 — UI mocked in v0.dev → developed and refined inside Cursor",
      "Step 5 — Claude generates QA checklist → edge cases surfaced before delivery",
      "Step 6 — Claude writes handoff doc → automation sends it + testimonial request",
    ],
  },
  "content-creator": {
    title: "Content Creator",
    description:
      "Scripts, thumbnails, and publishing workflows—all from one place.",
    whoThisIsFor: [
      "YouTubers and video creators",
      "Podcasters and streamers",
      "Social media managers",
    ],
    tools: [
      "Claude— ideation, scripting, hooks, titles, descriptions, captions",
      "ChatGPT — fast brainstorming and variation generation",
      "ElevenLabs— AI voiceover for faceless content or voiceover drafts",
      "Descript — AI-powered video editing, transcript-based editing, auto captions",
      "Opus Clip — auto-generates short clips from long-form video using AI",
      "Midjourney — thumbnail concept generation and visual ideation",
      "Make/Zapier— automate content distribution across platforms",
    ],
    steps: [
      "Step 1 — Topic idea → Claude generates 10 angle options in 60 seconds",
      "Step 2 — Best angle → Claude writes full script with hook, body, CTA",
      "Step 3 — Script recorded → Descript handles editing via transcript",
      "Step 4 — Long video published → Opus Clip auto-cuts 5–10 Reels/Shorts",
      "Step 5 — Claude writes title, description, tags, and captions per platform",
      "Step 6 — Automation schedules and cross-posts to all platforms",
    ],
  },
  marketing: {
    title: "Marketing",
    description:
      "Campaigns, copy, and analytics in a single streamlined workflow.",
    whoThisIsFor: [
      "Growth and marketing leads",
      "Content and brand teams",
      "Agencies managing multiple clients",
    ],
    tools: [
      "Claude— strategy, long-form copy, email sequences, campaign briefs, reports",
      "ChatGPT— fast variation generation, quick brainstorms, social captions",
      "Jasper/Copy.ai— ad copy and landing page copy at scale",
      "Surfer SEO+ Claude — SEO content briefs and optimized article drafts",
      "Canva AI— visual content generation without a designer",
      "Make/ Zapier — automate reporting, publishing, and lead workflows",
      "Notion AI — campaign planning, content banks, living strategy docs",
    ],
    steps: [
      "Step 1 — Goal defined → Claude builds full campaign strategy in 30 min",
      "Step 2 — Strategy approved → Claude writes all copy (ads, emails, landing pages)",
      "Step 3 — Content calendar generated → 30 days of posts planned in one session",
      "Step 4 — Campaign live → AI monitors performance and flags what to change",
      "Step 5 — Week ends → automated performance report sent to client or leadership",
      "Step 6 — Content repurposed → one asset becomes 8 formats automatically",
    ],
  },
  student: {
    title: "Student",
    description:
      "Notes, summaries, and study plans that adapt to your schedule.",
    whoThisIsFor: [
      "College and grad students",
      "Lifelong learners",
      "Professionals prepping for certifications",
    ],
    tools: [
      "Claude— understanding complex topics, essay planning, research synthesis, feedback",
      "ChatGPT— quick explanations, concept breakdowns, flashcard generation",
      "Notion AI — organized notes, study plans, living knowledge base",
      "Perplexity AI— cited research answers that replace 10 browser tabs",
      "Anki+ AI — spaced repetition flashcards generated by AI, studied by you",
      "Otter.ai — auto-transcribes lectures so you never miss what was said",
      "Grammarly— grammar and clarity checks before submitting any assignment",
    ],
    steps: [
      "Step 1 — New topic assigned → Claude explains it like a tutor in 5 minutes",
      "Step 2 — Lecture recorded → Otter.ai transcribes → Claude extracts key points",
      "Step 3 — Essay or assignment due → Claude builds outline, you write the sections",
      "Step 4 — Draft written → Claude gives structured feedback before submission",
      "Step 5 — Exam approaching → AI generates flashcards and practice questions",
      "Step 6 — Revision session → Anki runs spaced repetition, Claude quizzes you",
    ],
  },
  "startup-founder": {
    title: "Startup Founder",
    description:
      "Pitch decks, hiring checklists, and ops—less chaos, more clarity.",
    whoThisIsFor: [
      "First-time and solo founders",
      "Early-stage startup teams",
      "Operators wearing many hats",
    ],
    tools: [
      "Claude — strategy, investor materials, customer research synthesis, hiring, legal drafts",
      "ChatGPT— fast ideation, competitive analysis, pitch practice",
      "Notion AI— company wiki, meeting notes, OKRs, living product roadmap",
      "Perplexity AI— real-time market research with cited sources",
      "Cursor IDE / GitHub Copilot — AI-assisted product development for technical founders",
      "Make / Zapier — operational automation, CRM workflows, onboarding sequences",
      "Otter.ai — transcribe customer calls automatically for research",
    ],
    steps: [
      "Step 1 — New idea or decision → Claude stress-tests it before you build",
      "Step 2 — Customer calls recorded → AI extracts insights, patterns, and signals",
      "Step 3 — Fundraising needed → Claude drafts pitch deck narrative and investor emails",
      "Step 4 — Hiring begins → AI writes job posts, screens answers, drafts offer letters",
      "Step 5 — Operations pile up → automations handle recurring tasks without founder time",
      "Step 6 — Weekly review → AI synthesizes what happened and what to prioritize next",
    ],
  },
};

type PageProps = { params: Promise<{ id: string }> };

export default async function WorkflowPage({ params }: PageProps) {
  const { id } = await params;
  const workflow = WORKFLOWS[id];

  if (!workflow) notFound();

  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white font-sans">
      <nav className="flex items-center justify-between px-8 py-5 border-b border-white/10 max-w-7xl mx-auto w-full">
        <Link href="/" className="text-2xl font-bold tracking-tight text-white">
          Crazly
        </Link>
        <div className="flex items-center gap-8">
          <Link href="/workflows" className="text-sm text-white font-medium">
            Workflows
          </Link>
          <a
            href="#"
            className="text-sm text-white/60 hover:text-white transition-colors"
          >
            Pricing
          </a>
          <a
            href="#"
            className="text-sm bg-white text-black font-semibold px-4 py-2 rounded-lg hover:bg-white/90 transition-colors"
          >
            Get Started
          </a>
        </div>
      </nav>

      <article className="max-w-3xl mx-auto px-6 py-12">
        <header className="mb-12">
          <Link
            href="/workflows"
            className="text-sm text-white/50 hover:text-white transition-colors inline-flex items-center gap-1.5 mb-6"
          >
            ← Back to Workflows
          </Link>
          <h1 className="text-3xl font-bold tracking-tight text-white mb-3">
            {workflow.title}
          </h1>
          <p className="text-white/50 leading-relaxed">
            {workflow.description}
          </p>
        </header>

        <div className="space-y-10">
          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wider text-white/40 mb-4">
              Who this is for
            </h2>
            <ul className="space-y-2">
              {workflow.whoThisIsFor.map((item) => (
                <li
                  key={item}
                  className="text-white/80 flex items-center gap-2"
                >
                  <span className="text-indigo-400">•</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wider text-white/40 mb-4">
              Tools
            </h2>
            <div className="flex flex-wrap gap-2">
              {workflow.tools.map((tool) => (
                <span
                  key={tool}
                  className="px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-sm text-white/80"
                >
                  {tool}
                </span>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-sm font-semibold uppercase tracking-wider text-white/40 mb-4">
              Workflow Steps
            </h2>
            <ol className="space-y-3">
              {workflow.steps.map((step, i) => (
                <li
                  key={i}
                  className="flex gap-3 text-white/80"
                >
                  <span className="shrink-0 w-6 h-6 rounded-full bg-white/10 flex items-center justify-center text-xs font-medium text-white/60">
                    {i + 1}
                  </span>
                  {step}
                </li>
              ))}
            </ol>
          </section>

          <section className="relative">
            <h2 className="text-sm font-semibold uppercase tracking-wider text-white/40 mb-4">
              Premium section locked
            </h2>
            <div className="relative rounded-xl border border-white/10 overflow-hidden">
              <div className="blur-md select-none pointer-events-none bg-white/5 p-8 min-h-[200px]">
                <p className="text-white/30 text-sm mb-4">
                  Advanced automation rules and conditional logic for this
                  workflow. Connect custom integrations, set up triggers, and
                  run multi-step sequences.
                </p>
                <ul className="space-y-2 text-white/20 text-sm">
                  <li>• Conditional branches</li>
                  <li>• Webhook triggers</li>
                  <li>• Custom API steps</li>
                  <li>• Priority support</li>
                </ul>
              </div>
              <div className="absolute inset-0 flex items-center justify-center bg-black/40 backdrop-blur-sm">
                <div className="text-center px-6">
                  <p className="text-white font-semibold mb-4">
                    Unlock full workflow with Crazly Pro
                  </p>
                  <button
                    type="button"
                    className="text-sm font-medium px-5 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-colors"
                  >
                    Upgrade to Pro
                  </button>
                </div>
              </div>
            </div>
          </section>
        </div>
      </article>
    </main>
  );
}
